//! gRPC ingress: the proxy's `DocumentService` over HTTP/2 (`docs/11` M4).
//!
//! gRPC is a *front door*, not a second pipeline. Each RPC is adapted into the
//! same owned [`IngressRequest`] the REST path produces — same endpoint
//! classification, same headers-as-credentials contract — and driven through the
//! identical [`IngressHandler`]. Tenancy, isolation, and shape-only observability
//! are therefore unchanged across protocols; only the wire envelope differs.
//!
//! The generated server stubs and prost messages come from `proto/osproxy.proto`
//! (compiled in `build.rs` into `OUT_DIR`), pulled in below.

use std::sync::Arc;

use osproxy_spi::HttpMethod;
use tokio::net::TcpListener;
use tokio_stream::wrappers::TcpListenerStream;
use tonic::{Request, Response, Status};

use crate::classify::classify;
use crate::handler::IngressHandler;
use crate::request::IngressRequest;

mod pb {
    // Generated by `tonic-prost-build`; not our code to lint or document.
    #![allow(
        clippy::pedantic,
        clippy::nursery,
        clippy::all,
        missing_docs,
        unreachable_pub,
        dead_code
    )]
    tonic::include_proto!("osproxy.v1");
}

use pb::document_service_server::{DocumentService, DocumentServiceServer};
use pb::{IndexReply, IndexRequest};

/// The metadata key carrying a bearer token, mapped to an `authorization`
/// header so the shared handler authenticates a gRPC caller the same way.
const AUTHORIZATION: &str = "authorization";

/// Adapts the transport's [`IngressHandler`] to the generated gRPC service.
struct GrpcIngress<H> {
    handler: Arc<H>,
}

#[tonic::async_trait]
impl<H: IngressHandler> DocumentService for GrpcIngress<H> {
    async fn index(&self, request: Request<IndexRequest>) -> Result<Response<IndexReply>, Status> {
        let headers = bearer_header(&request);
        let msg = request.into_inner();

        // Synthesize the REST request this RPC stands for, then classify it the
        // same way, so the endpoint/index/doc-id are derived by one code path.
        let (method, path) = if msg.id.is_empty() {
            (HttpMethod::Post, format!("/{}/_doc", msg.index))
        } else {
            (HttpMethod::Put, format!("/{}/_doc/{}", msg.index, msg.id))
        };
        let c = classify(method, &path);

        let ingress = IngressRequest {
            method,
            path,
            endpoint: c.endpoint,
            logical_index: c.logical_index,
            doc_id: c.doc_id,
            headers,
            body: msg.document,
            // mTLS identity for the gRPC listener attaches with its TLS slice.
            client_cert_subject: None,
        };

        let resp = self.handler.handle(ingress).await;
        let request_id = resp
            .headers
            .iter()
            .find(|(k, _)| k.eq_ignore_ascii_case("x-request-id"))
            .map(|(_, v)| v.clone())
            .unwrap_or_default();

        Ok(Response::new(IndexReply {
            status: u32::from(resp.status),
            body: resp.body,
            request_id,
        }))
    }
}

/// Extracts a bearer token from the request metadata into an `authorization`
/// header, so the shared credential extraction (`Bearer …`) works unchanged.
/// The token is carried, never logged — the handler consumes it (NFR-S2).
fn bearer_header<T>(request: &Request<T>) -> Vec<(String, String)> {
    request
        .metadata()
        .get(AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .map(|token| vec![(AUTHORIZATION.to_owned(), token.to_owned())])
        .unwrap_or_default()
}

/// Serves the gRPC `DocumentService` on `listener`, dispatching each RPC through
/// `handler` (the same pipeline the HTTP ingress drives), until it errors.
///
/// # Errors
///
/// Returns the transport error if serving fails (bind/accept/protocol).
pub async fn serve_grpc<H: IngressHandler>(
    listener: TcpListener,
    handler: Arc<H>,
) -> Result<(), tonic::transport::Error> {
    let service = DocumentServiceServer::new(GrpcIngress { handler });
    tonic::transport::Server::builder()
        .add_service(service)
        .serve_with_incoming(TcpListenerStream::new(listener))
        .await
}

#[cfg(test)]
mod tests {
    use std::sync::Mutex;

    use osproxy_core::EndpointKind;

    use super::pb::document_service_client::DocumentServiceClient;
    use super::*;
    use crate::request::IngressResponse;

    /// Records the request it was handed and replies with a fixed response, so
    /// the test can assert the gRPC adapter built the right `IngressRequest`.
    #[derive(Default)]
    struct RecordingHandler {
        seen: Mutex<Option<IngressRequest>>,
    }

    impl IngressHandler for RecordingHandler {
        async fn handle(&self, req: IngressRequest) -> IngressResponse {
            *self.seen.lock().expect("lock") = Some(req);
            IngressResponse::json(201, br#"{"result":"created"}"#.to_vec())
                .with_header("x-request-id", "req-7")
        }
    }

    #[tokio::test]
    async fn index_rpc_drives_the_shared_handler_and_maps_the_reply() {
        let listener = TcpListener::bind("127.0.0.1:0").await.expect("bind");
        let addr = listener.local_addr().expect("addr");
        let handler = Arc::new(RecordingHandler::default());
        let handler_for_server = Arc::clone(&handler);
        tokio::spawn(async move { serve_grpc(listener, handler_for_server).await });

        let mut client = DocumentServiceClient::connect(format!("http://{addr}"))
            .await
            .expect("connect");
        let reply = client
            .index(IndexRequest {
                index: "orders".to_owned(),
                id: "acme:1".to_owned(),
                document: br#"{"msg":"hi"}"#.to_vec(),
            })
            .await
            .expect("rpc")
            .into_inner();

        // The reply faithfully carries the handler's response and request id.
        assert_eq!(reply.status, 201);
        assert_eq!(reply.request_id, "req-7");
        assert_eq!(reply.body, br#"{"result":"created"}"#);

        // The adapter synthesized a REST-equivalent ingest request: a PUT (id
        // present) to `_doc/{id}`, classified as a single-doc ingest.
        let seen = handler.seen.lock().expect("lock").clone().expect("seen");
        assert_eq!(seen.method, HttpMethod::Put);
        assert_eq!(seen.path, "/orders/_doc/acme:1");
        assert_eq!(seen.endpoint, EndpointKind::IngestDoc);
        assert_eq!(seen.logical_index, "orders");
        assert_eq!(seen.doc_id.as_deref(), Some("acme:1"));
        assert_eq!(seen.body, br#"{"msg":"hi"}"#);
    }
}
